spring:
  datasource:
    # -------------------
    # - postgres ??
    # -------------------
    url: jdbc:postgresql://localhost:5432/testdb
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging.level:
  com.kenny.com.kenny.postgrescompositepksequencesample: DEBUG
  org.hibernate.type: TRACE

